### ISSUE TITLE
[Split into multiple issues] regression : lost of functionalities in 3rd screen

### ISSUE THREAD

**Issue by MartineMK35** [kitamstudios/digitalpalireader#107]
![option lost on thrid screen](https://user-images.githubusercontent.com/61345779/75089500-bf68fb00-5559-11ea-8842-48f1f9297eea.PNG)

**Comment by dangeol** [comment]
This will be implemented after alpha release.

**Comment by parthopdas** [comment]
@MartineMK35 we are going to implement cj, cv and bv for sure in beta. 

Can you please tell if Tr, Tp and D are high in priority for beta or can we get them done post beta.?

**Comment by MartineMK35** [comment]
Ho Partho
No High Priority.. I think Cv could be nice for Thai,Singalese users if not
too complicated.....

Le mer. 4 mars 2020 à 03:01, Partho P. Das <notifications@github.com> a
écrit :

**Comment by parthopdas** [comment]
@MartineMK35 I have split this into 5 issues, all for beta: #128, #153, #154, #155, #156.
