### ISSUE TITLE
current word not underligned (regression)

### ISSUE THREAD

**Issue by MartineMK35** [kitamstudios/digitalpalireader#108]
![loss of thr word in the text 2](https://user-images.githubusercontent.com/61345779/75089529-0525c380-555a-11ea-93aa-db6eff6daf0f.PNG)
![loss of the word in the text](https://user-images.githubusercontent.com/61345779/75089531-0820b400-555a-11ea-8a2f-517664b17ea3.PNG)

**Comment by bksubhuti** [comment]
Yes.. I was just telling someone that .  So when you go to the definition, you forget where your place was.. and then you have to read the whole section again just to find that place again.  It is annoying.  I'd like to see it highlighted once you go to the definition mode.  That would be better.

**Comment by parthopdas** [comment]
@shraddha314 please verify and close.
