### ISSUE TITLE
[UX Structure] Buddha vachana in landing page

### ISSUE THREAD

**Issue by parthopdas** [kitamstudios/digitalpalireader#128]
AC
- [x] BV is available on landing page
- [x] BV is properly formatted 
- [x] BV that have long texts are displayed well
- [x] All links inside BV works

Note:
- this is the Bv tab from the palemoon DPR
   ![image](https://user-images.githubusercontent.com/2140460/75780186-a0166d00-5da6-11ea-8496-0529c4ab667d.png)

**Comment by sumbodhi** [comment]
![image](https://user-images.githubusercontent.com/61728359/76684774-60a61700-6617-11ea-96bb-b02cc06f57aa.png)

@parthopdas please provide the following details:
- should both - (1) Welcome/Intro message and (2) Daily Buddha Vacana be shown in the landing page?
- should the DBV text be centered (as in the screenshot)
- What do you mean with "Larger BV" should be displayed "well"?

**Comment by parthopdas** [comment]
@sumbodhi this looks great.
answers:
1. yes - please provide suggestions if you have better alternatives. @shraddha314 will evaluate that once she is back next month.
2. yes, but perhaps with some demarcation
3. I mean the BVs that are multiple lines long should display properly/fully. also corrected the AC regarding this.

**Comment by vasiltabakov** [comment]
I've just pushed the changes necessary to have that on the home page. But now I see a few things have changed, there are tabs in the bottom panel including Buddha Vacana. Are those two areas independent (vacana on home page and in the bottom panel)? @parthopdas depending on your answer more changes will be necessary.

**Comment by sumbodhi** [comment]
I've just pushed the changes necessary to have that on the home page. But now I see a few things have changed, there are tabs in the bottom panel including Buddha Vacana. Are those two areas independent (vacana on home page and in the bottom panel)? @parthopdas depending on your answer more changes will be necessary.

**Comment by parthopdas** [comment]
>, there are tabs in the bottom panel including Buddha Vacana. Are those two areas independent (vacana on home page and in the bottom panel)?

There is no bv tab in the bottom pane. 

Bv will just be a feature of the landing page. We want to greet people with that feature.

**Comment by vasiltabakov** [comment]
oh, then great, you can go ahead and merge the PR

**Comment by sumbodhi** [comment]
oh, then great, you can go ahead and merge the PR

**Comment by parthopdas** [comment]
@shraddha314 please verify and close.
