### ISSUE TITLE
Directory Structure has HTML as a minor project

### ISSUE THREAD

**Issue by bksubhuti** [kitamstudios/digitalpalireader#136]
The directory struture is organized with HTML as a minor project when in fact it is the major project.  While it will be tedious to move to the top root, I think it might be worth the task instead of following legacy directory organization.  This will also possibly help the PWA project's success by having things organized better.  Suttacentral has problems with their PWA being fully off line.

Lastly, if this fails or if it is desired, it leaves room for an option to have an offline client side app.  So the benefits are 3fold.
1.  Better organization
2.  Better success for PWA
3.  Option for client side app

**Comment by bksubhuti** [comment]
The web address also has HTML as a subdirectory.  It is not very pretty and lengthens the already long webaddress.

**Comment by parthopdas** [comment]
The necessary changes will be done with #126 and #96
