### ISSUE TITLE
Dictionary: Deep links for DPR Analysis don't work

### ISSUE THREAD

**Issue by dangeol** [kitamstudios/digitalpalireader#52]
Deep links in the adress bar of the browser must also work for DPR analysis.

E.g. http://127.0.0.1:8080/DPRHTML/index.html?analysis=citta&frombox=1 or http://127.0.0.1:8080/DPRHTML/index.html?feature=dictionary&type=TIT&query=citta&opts=xv,xd,xm,xs,xa,xk,xy,hd&analysis=citta&frombox=1 should show the word analysis. 

I have not been able to resolve this problem. Please, another volunteer :)

**Comment by parthopdas** [comment]
@johnwang16 my apologies. I had requested sumukha to look into it without assigning it to him. I'll take care of that in the future. He is going to float a PR and I'll find you something else to work on.

**Comment by parthopdas** [comment]
@shraddha314 please verify and close.
