### ISSUE TITLE
Reproduce Project (and make it run) on a clean machine

### ISSUE THREAD

**Issue by bksubhuti** [kitamstudios/digitalpalireader#82]
This is an HTML project.  You should be able to 
1.  Download the zip.
2.  Change fileuri security
3.  Make it run by clicking on index.html
4.  Test this on a clean machine.  The best way is to make a bootable ubuntu usb with no persistence.
5.  Drop the zip in the document folder (or anywhere)
6. unzip
7.  change security.file.uri.strict on firefox (comes with ubuntu) 
8.  click on index.html inside the root of project (assuming the other issues of separating this project are done.
If this is successfully done, it should work on any type of platform except ios.  This will remove the need to "build" on windows.

**Comment by bksubhuti** [comment]
This project is able to run on a clean machine with live-server.
Is it possible to get this to work without a server?  If not maybe close this issue.
The fileuri allows access to local file and subfolders.

**Comment by parthopdas** [comment]
The the product strategy is to be web based, we will continue to require web-server. To server the offline scenario we are doing #126.

However I am happy to accept contributions in case you are able to make the project run from local files system.
